name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        ndk: 21.3.6528147
        script: |
            cmake -E make_directory ${{runner.workspace}}/build
            cd build
            cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE \
              -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$ANDROID_SDK_ROOT/ndk/21.3.6528147/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI:STRING=x86_64 \
              -DANDROID_PLATFORM:STRING=19 \
              -DANDROID_STL:STRING=c++_static
            cmake --build . --config $BUILD_TYPE --target run

    
